---
name: CI

on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yml

  tag:
    runs-on: ubuntu-latest
    needs: build
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0

      - name: Download vertag
        uses: robinraju/release-downloader@v1.8
        with:
          repository: gofrontier-com/vertag
          latest: true
          fileName: vertag_Linux_x86_64.tar.gz
          token: ${{ secrets.GITHUB_TOKEN }}
          extract: true

      - name: Run vertag
        run: |
          ./vertag apply \
            --modules-dir "${{ github.workspace }}/modules" \
            --repo "${{ github.workspace }}" \
            --author-name "Build bot" \
            --author-email "build.bot@gofrontier.com" \
            --remote-url https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/gofrontier-com/azurerm-terraform-modules
