---
name: Release

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
