---
name: Release

on:
  push:
    tags:
      - "**"

permissions:
  contents: write

jobs:
  build:
    uses: ./.github/workflows/build.yml

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4

      - run: echo $GITHUB_REF
